Repository agda/agda, pull requests merged in 2019-07, with the labels that each got.

#3887 [ fixed #3886 ] by adding origin to Quantity
  src/full/Agda/Syntax/Common.hs
  src/full/Agda/Syntax/Concrete/Attribute.hs
  src/full/Agda/Syntax/Concrete/Pretty.hs
  src/full/Agda/Syntax/Position.hs
  src/full/Agda/TypeChecking/Errors.hs
  src/full/Agda/TypeChecking/Forcing.hs
  src/full/Agda/TypeChecking/Free/Lazy.hs
  src/full/Agda/TypeChecking/Irrelevance.hs
  src/full/Agda/TypeChecking/Monad/Base.hs
  src/full/Agda/TypeChecking/Pretty.hs
  src/full/Agda/TypeChecking/Rules/Application.hs
  src/full/Agda/TypeChecking/Rules/Decl.hs
  src/full/Agda/TypeChecking/Rules/LHS/Unify.hs
  src/full/Agda/TypeChecking/Rules/Term.hs
  src/full/Agda/TypeChecking/Serialise.hs
  src/full/Agda/TypeChecking/Serialise/Instances/Common.hs
  test/Compiler/simple/Issue3886.agda
  test/Compiler/simple/Issue3886.out
  test/Fail/Erasure-Lambda-Wrong-Attribute.err
  test/Fail/Issue1886-modality.err
  test/Fail/Issue3323q.err
  test/Internal/Syntax/Common.hs
  test/interaction/UnderappliedConstructor.out
Labels: status: do-not-merge

#3896 [ fix ] `make install-bin` with stack.yaml compiles Agda only once
  Makefile
Labels: not-in-changelog

#3899 [ dev ] `quicker-install-bin` for stack
  .gitignore
  Makefile
Labels: not-in-changelog

#3908 Issue 3792
  src/full/Agda/Compiler/ToTreeless.hs
  src/full/Agda/Compiler/Treeless/Erase.hs
  src/full/Agda/Compiler/Treeless/Simplify.hs
  src/full/Agda/Compiler/Treeless/Subst.hs
Labels: status: do-not-merge

#3906 [ #3905 ] tasty test with --ansi-tricks=false on travis
  .travis.yml
  Agda.cabal
  stack-8.0.2.yaml
  stack-8.2.2.yaml
  stack-8.4.4.yaml
  stack-8.6.5.yaml
Labels: not-in-changelog, travis

#3914 [ stack ] Bump to LTS 13.28 for GHC 8.6.5
  stack-8.0.2.yaml
  stack-8.2.2.yaml
  stack-8.4.4.yaml
  stack-8.6.5.yaml
Labels: hackage, not-in-changelog, stackage

#3920 [ refactor / cabal ] Remove DataKind from Agda.cabal
  Agda.cabal
  src/full/Agda/Interaction/Options.hs
  src/full/Agda/Syntax/Concrete/Operators/Parser.hs
  src/full/Agda/TypeChecking/Serialise/Base.hs
  src/full/Agda/Utils/IndexedList.hs
  src/full/Agda/Utils/TypeLevel.hs
  src/full/Agda/Utils/TypeLits.hs
  src/full/Agda/Utils/WithDefault.hs
Labels: refactor

#3902 Forcing #3898
  Agda.cabal
  src/full/Agda/Interaction/Options.hs
  src/full/Agda/Syntax/Concrete/Operators/Parser.hs
  src/full/Agda/TypeChecking/Serialise/Base.hs
  src/full/Agda/Utils/IndexedList.hs
  src/full/Agda/Utils/TypeLevel.hs
  src/full/Agda/Utils/TypeLits.hs
  src/full/Agda/Utils/WithDefault.hs
Labels: forcing

#3922 [ refactor ] Remove unused top-level bindings
  src/full/Agda/Compiler/Treeless/Pretty.hs
  src/full/Agda/Interaction/Highlighting/LaTeX.hs
  src/full/Agda/Interaction/Library.hs
  src/full/Agda/Interaction/Library/Parse.hs
  src/full/Agda/Interaction/Options.hs
  src/full/Agda/Syntax/Concrete.hs
  src/full/Agda/Syntax/Concrete/Definitions.hs
  src/full/Agda/Syntax/Concrete/Fixity.hs
  src/full/Agda/Syntax/Parser/LookAhead.hs
  src/full/Agda/Syntax/Parser/Monad.hs
  src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs
  src/full/Agda/Syntax/Translation/InternalToAbstract.hs
  src/full/Agda/Termination/TermCheck.hs
  src/full/Agda/TypeChecking/CheckInternal.hs
  src/full/Agda/TypeChecking/Coverage/Match.hs
  src/full/Agda/TypeChecking/Free.hs
  src/full/Agda/TypeChecking/RecordPatterns.hs
  src/full/Agda/TypeChecking/Reduce/Fast.hs
  src/full/Agda/TypeChecking/Rules/Display.hs
  src/full/Agda/TypeChecking/Rules/LHS.hs
  src/full/Agda/TypeChecking/Rules/LHS/Problem.hs
  src/full/Agda/TypeChecking/Rules/LHS/Unify.hs
  src/full/Agda/TypeChecking/Warnings.hs
  src/full/Agda/Utils/FileName.hs
  src/full/Agda/Utils/Parser/MemoisedCPS.hs
Labels: refactor

#3924 [ refactor ] Remove unused imports with an empty import list
  src/full/Agda/Benchmarking.hs
  src/full/Agda/Compiler/Backend.hs
  src/full/Agda/Compiler/MAlonzo/HaskellTypes.hs
  src/full/Agda/Compiler/ToTreeless.hs
  src/full/Agda/Compiler/Treeless/Builtin.hs
  src/full/Agda/Compiler/Treeless/Compare.hs
  src/full/Agda/Compiler/Treeless/EliminateDefaults.hs
  src/full/Agda/Compiler/Treeless/Simplify.hs
  src/full/Agda/Compiler/Treeless/Unused.hs
  src/full/Agda/Interaction/InteractionTop.hs
  src/full/Agda/Interaction/JSONTop.hs
  src/full/Agda/Main.hs
  src/full/Agda/Syntax/Abstract.hs
  src/full/Agda/Syntax/Abstract/Pretty.hs
  src/full/Agda/Syntax/Concrete/Attribute.hs
  src/full/Agda/Syntax/Concrete/Definitions.hs
  src/full/Agda/Syntax/Concrete/Operators.hs
  src/full/Agda/Syntax/Parser.hs
  src/full/Agda/Syntax/Parser/Parser.y
  src/full/Agda/TypeChecking/CompiledClause/Match.hs
  src/full/Agda/TypeChecking/Coverage/SplitTree.hs
  src/full/Agda/TypeChecking/EtaContract.hs
  src/full/Agda/TypeChecking/IApplyConfluence.hs
  src/full/Agda/TypeChecking/InstanceArguments.hs
  src/full/Agda/TypeChecking/Level.hs
  src/full/Agda/TypeChecking/Monad/SizedTypes.hs
  src/full/Agda/TypeChecking/Names.hs
  src/full/Agda/TypeChecking/Patterns/Internal.hs
  src/full/Agda/TypeChecking/Pretty/Warning.hs
  src/full/Agda/TypeChecking/Primitive.hs
  src/full/Agda/TypeChecking/Records.hs
  src/full/Agda/TypeChecking/Reduce/Monad.hs
  src/full/Agda/TypeChecking/Serialise.hs
  src/full/Agda/TypeChecking/Serialise/Instances.hs
  src/full/Agda/TypeChecking/Serialise/Instances/Abstract.hs
  src/full/Agda/TypeChecking/Serialise/Instances/Errors.hs
  src/full/Agda/TypeChecking/Serialise/Instances/Highlighting.hs
  src/full/Agda/TypeChecking/Serialise/Instances/Internal.hs
  src/full/Agda/TypeChecking/Sort.hs
  src/full/Agda/Utils/Bag.hs
  src/full/Agda/Utils/List.hs
Labels: import, refactor

#3863 [ fix #3851 ] Return the type of the generated helper as is
  src/data/emacs-mode/agda2-mode.el
Labels: agda-mode, emacs, generate-helper, interaction, refactor

#3929 [ fix #3879 ] Resugar fewer pattern synonyms
  src/full/Agda/Syntax/Translation/AbstractToConcrete.hs
  test/interaction/Issue3879.agda
  test/interaction/Issue3879.in
  test/interaction/Issue3879.out
  test/interaction/Issue3879/Fin.agda
Labels: pattern-synonyms, printing

#3880 [ new ] irrefutable with-matches on the LHS
  CHANGELOG.md
  doc/user-manual/language/with-abstraction.lagda.rst
  src/full/Agda/Syntax/Abstract.hs
  src/full/Agda/Syntax/Abstract/Views.hs
  src/full/Agda/Syntax/Common.hs
  src/full/Agda/Syntax/Concrete.hs
  src/full/Agda/Syntax/Concrete/Generic.hs
  src/full/Agda/Syntax/Concrete/Pretty.hs
  src/full/Agda/Syntax/Parser/Parser.y
  src/full/Agda/Syntax/Translation/AbstractToConcrete.hs
  src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs
  src/full/Agda/TypeChecking/Rules/Def.hs
  src/full/Agda/Utils/Either.hs
  src/full/Agda/Utils/Pretty.hs
  test/Succeed/UsingEq.agda
Labels: language-change, type: discussion, type: enhancement

#3884 [ fix #1097 ] more liberal syntax in telescopes
  CHANGELOG.md
  doc/user-manual/language/telescopes.lagda.rst
  src/full/Agda/Auto/Convert.hs
  src/full/Agda/Interaction/BasicOps.hs
  src/full/Agda/Interaction/Highlighting/Generate.hs
  src/full/Agda/Interaction/MakeCase.hs
  src/full/Agda/Syntax/Abstract.hs
  src/full/Agda/Syntax/Common.hs
  src/full/Agda/Syntax/Concrete.hs
  src/full/Agda/Syntax/Concrete/Operators/Parser.hs
  src/full/Agda/Syntax/Concrete/Pretty.hs
  src/full/Agda/Syntax/DoNotation.hs
  src/full/Agda/Syntax/Parser/Parser.y
  src/full/Agda/Syntax/Scope/Base.hs
  src/full/Agda/Syntax/Scope/Monad.hs
  src/full/Agda/Syntax/Translation/AbstractToConcrete.hs
  src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs
  src/full/Agda/Syntax/Translation/InternalToAbstract.hs
  src/full/Agda/Syntax/Translation/ReflectedToAbstract.hs
  src/full/Agda/TypeChecking/Errors.hs
  src/full/Agda/TypeChecking/Generalize.hs
  src/full/Agda/TypeChecking/Monad/Base.hs
  src/full/Agda/TypeChecking/Rules/Data.hs
  src/full/Agda/TypeChecking/Rules/Term.hs
  src/full/Agda/TypeChecking/Serialise/Instances/Abstract.hs
  test/Fail/Issue1391c.err
  test/Fail/Issue1391d.err
  test/Succeed/AsInTele.agda
Labels: as-patterns, language-change, type: enhancement
