Repository agda/agda, pull requests merged in 2020-05, with the labels that each got.

#4640 add fixity change howto to Precedence
  doc/user-manual/language/mixfix-operators.lagda.rst
Labels: documentation

#4636 Fix tiny typo in documentation
  doc/user-manual/language/with-abstraction.lagda.rst
Labels: documentation

#3395 Js backend small improvements
  CHANGELOG.md
  doc/user-manual/tools/compilers.lagda.rst
  src/full/Agda/Compiler/JS/Compiler.hs
  src/full/Agda/Compiler/JS/Pretty.hs
  src/full/Agda/Compiler/JS/Substitution.hs
  src/full/Agda/Compiler/JS/Syntax.hs
  test/Compiler/Tests.hs
Labels: js-backend

#4639 Better error message for illegal type signatures in mutual blocks
  src/full/Agda/Syntax/Scope/Monad.hs
  src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs
  src/full/Agda/TypeChecking/Errors.hs
  src/full/Agda/TypeChecking/Monad/Base.hs
  test/Fail/Issue4435-1.agda
  test/Fail/Issue4435-1.err
  test/Fail/Issue4435-2.agda
  test/Fail/Issue4435-2.err
Labels: data, error-reporting, mutual, scope

#4669 Allow aeson 1.5
  Agda.cabal
Labels: installation, interaction-json

#4645 [ fix #4572 ] added piSort UnivSort funSort and Setω+n to the user-manual
  doc/user-manual/language/index.rst
  doc/user-manual/language/lexical-structure.lagda.rst
  doc/user-manual/language/sort-system.lagda.rst
Labels: documentation, status: ready

#4546 [ new ] use text for string literals
  src/full/Agda/Compiler/JS/Compiler.hs
  src/full/Agda/Compiler/JS/Pretty.hs
  src/full/Agda/Compiler/JS/Syntax.hs
  src/full/Agda/Compiler/MAlonzo/Compiler.hs
  src/full/Agda/Compiler/MAlonzo/Misc.hs
  src/full/Agda/Compiler/MAlonzo/Pretty.hs
  src/full/Agda/Compiler/MAlonzo/Primitives.hs
  src/full/Agda/Interaction/BasicOps.hs
  src/full/Agda/Interaction/Imports.hs
  src/full/Agda/Syntax/Concrete.hs
  src/full/Agda/Syntax/Concrete/Pretty.hs
  src/full/Agda/Syntax/Literal.hs
  src/full/Agda/Syntax/Parser/StringLiterals.hs
  src/full/Agda/Syntax/Translation/InternalToAbstract.hs
  src/full/Agda/TypeChecking/Monad/Base.hs
  src/full/Agda/TypeChecking/Pretty/Warning.hs
  src/full/Agda/TypeChecking/Primitive.hs
  src/full/Agda/TypeChecking/Quote.hs
  src/full/Agda/TypeChecking/Reduce/Fast.hs
  src/full/Agda/TypeChecking/Serialise.hs
  src/full/Agda/TypeChecking/Serialise/Base.hs
  src/full/Agda/TypeChecking/Serialise/Instances/Common.hs
  src/full/Agda/TypeChecking/Unquote.hs
  src/full/Agda/Utils/Haskell/Syntax.hs
  test/Internal/TypeChecking/Generators.hs
  test/interaction/Issue3831.out
Labels: status: work-in-progress
