Repository agda/agda, pull requests merged in 2020-06, with the labels that each got.

#4699 <record-name>.constructor instead of recCon-NOT-PRINTED
  src/full/Agda/TypeChecking/Rules/Record.hs
  test/Fail/Issue1944-UnappliedOverloadedProjectionNotRecord.err
Labels: printing, printing-state, record-constructor

#4673 [ fix #3874 ] updated core language in user manual
  doc/user-manual/language/core-language.lagda.rst
  doc/user-manual/language/let-and-where.lagda.rst
  doc/user-manual/language/mixfix-operators.lagda.rst
  doc/user-manual/language/module-system.lagda.rst
  doc/user-manual/tools/compilers.lagda.rst
Labels: documentation, status: being-reviewed

#4719 [ fix #4696 ] Print file & line of raised error at verbosity 2
  src/full/Agda/Interaction/BasicOps.hs
  src/full/Agda/Interaction/Highlighting/Generate.hs
  src/full/Agda/Interaction/Imports.hs
  src/full/Agda/Interaction/InteractionTop.hs
  src/full/Agda/Syntax/Common.hs
  src/full/Agda/Syntax/Concrete/Definitions.hs
  src/full/Agda/Syntax/Concrete/Fixity.hs
  src/full/Agda/Syntax/Scope/Monad.hs
  src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs
  src/full/Agda/TypeChecking/Constraints.hs
  src/full/Agda/TypeChecking/Errors.hs
  src/full/Agda/TypeChecking/InstanceArguments.hs
  src/full/Agda/TypeChecking/MetaVars/Occurs.hs
  src/full/Agda/TypeChecking/Monad/Base.hs
  src/full/Agda/TypeChecking/Pretty/Warning.hs
  src/full/Agda/TypeChecking/Pretty/Warning.hs-boot
  src/full/Agda/TypeChecking/Rewriting/Confluence.hs
  src/full/Agda/TypeChecking/Rules/LHS.hs
  src/full/Agda/TypeChecking/Rules/Term.hs
  src/full/Agda/TypeChecking/Serialise.hs
  src/full/Agda/TypeChecking/Serialise/Instances/Errors.hs
  src/full/Agda/TypeChecking/Warnings.hs
Labels: debug, type: enhancement

#4739 Added documentation on installing multiple versions of Agda
  doc/user-manual/getting-started/installation.rst
Labels: documentation

#4742 [ interaction ] Constraints overlapping metas not highlighted
  src/full/Agda/Interaction/Highlighting/Generate.hs
  src/full/Agda/Interaction/Highlighting/Range.hs
  src/full/Agda/Interaction/InteractionTop.hs
  src/full/Agda/Utils/List.hs
  test/Internal/Interaction/Highlighting/Range.hs
Labels: constraints, highlighting, interaction

#4746 Install fix-whitespace instead of building it
  Makefile
Labels: fix-agda-whitespace, not-in-changelog

#4753 Recent ubuntu for build
  .github/workflows/cabal.yml
  .github/workflows/haddock.yml
  .github/workflows/nightly.yml
  .github/workflows/stack.yml
  .github/workflows/user_manual.yml
  .github/workflows/whitespace.yml
  .travis.yml
  stack-8.0.2.yaml
  stack-8.2.2.yaml
  stack-8.4.4.yaml
  stack-8.6.5.yaml
  stack-8.8.2.yaml
  stack-8.8.3.yaml
Labels: github-workflows, travis
