Repository agda/agda, pull requests merged in 2021-11, with the labels that each got.

#5623 Added a pragma to the 'Hello world' program example with the standard library
  doc/user-manual/getting-started/a-taste-of-agda.lagda.rst
Labels: documentation, hello-world

#5621 [ user manual ] Add warning not to install emacs-mode from melpa
  doc/user-manual/getting-started/installation.rst
Labels: installation, agda-mode, status: changes requested, user-manual

#5640 Some changes related to the DOT backend
  CHANGELOG.md
  doc/user-manual/tools/command-line-options.rst
  doc/user-manual/tools/package-system.rst
  src/full/Agda/Interaction/Highlighting/Dot/Backend.hs
  src/full/Agda/Interaction/Highlighting/Dot/Base.hs
  src/full/Agda/Interaction/Imports.hs
  src/full/Agda/TypeChecking/Monad/Options.hs
  src/full/Agda/Utils/Graph/AdjacencyMap/Unidirectional.hs
  test/Fail/Tests.hs
  test/Fail/customised/Issue5644.agda
  test/Fail/customised/Issue5644.err
  test/Fail/customised/Issue5644/A/B.agda
  test/Fail/customised/Issue5644/A/ignored.agda-lib
  test/Fail/customised/Issue5644/issue5644.agda-lib
  test/Internal/Utils/Graph/AdjacencyMap/Unidirectional.hs
  test/Succeed/Issue481.dot.orig
  test/Succeed/Issue481.flags
  test/Succeed/Tests.hs
Labels: type: enhancement, backend:dot

#5656 Don't warn about abstract alias if the type is a solved meta
  src/full/Agda/TypeChecking/Rules/Def.hs
  test/Succeed/Issue5620.agda
Labels: abstract

#5658 Fix #5657: isProjection might fail on an A.Proj, so, not IMPOSSIBLE
  src/full/Agda/TypeChecking/Rules/Application.hs
  test/Fail/Issue5657.agda
  test/Fail/Issue5657.err
Labels: regression in 2.6.2, internal-error, postfix-projections

#5653 Fixed #5441
  CHANGELOG.md
  doc/user-manual/tools/compilers.lagda.rst
  src/full/Agda/Compiler/MAlonzo/Compiler.hs
  test/Compiler/Tests.hs
  test/Compiler/simple/Issue5441.agda
  test/Compiler/simple/Issue5441.options
  test/Compiler/simple/Issue5441.out
Labels: backend:ghc

#5671 Relax upper bound of `hashtables` to < 1.4
  Agda.cabal
Labels: stackage
