Repository agda/agda, pull requests merged in 2023-12, with the labels that each got.

#7026 issue7020: add note about compilation of irrelevant fields
  doc/user-manual/tools/compilers.lagda.rst
Labels: irrelevance, backend: ghc, ux: documentation

#6897 Break cross-module SCC 4
  Agda.cabal
  Makefile
  src/full/Agda/Compiler/Backend.hs
  src/full/Agda/Compiler/Backend.hs-boot
  src/full/Agda/Compiler/Backend/Base.hs
  src/full/Agda/Compiler/Common.hs
  src/full/Agda/Compiler/JS/Compiler.hs
  src/full/Agda/Interaction/Base.hs
  src/full/Agda/Interaction/BasicOps.hs
  src/full/Agda/Interaction/EmacsTop.hs
  src/full/Agda/Interaction/Highlighting/Dot/Backend.hs
  src/full/Agda/Interaction/Highlighting/HTML/Backend.hs
  src/full/Agda/Interaction/Highlighting/LaTeX/Backend.hs
  src/full/Agda/Interaction/InteractionTop.hs
  src/full/Agda/Interaction/JSONTop.hs
  src/full/Agda/Interaction/Output.hs
  src/full/Agda/Interaction/Response.hs
  src/full/Agda/Interaction/Response.hs-boot
  src/full/Agda/Interaction/Response/Base.hs
  src/full/Agda/Syntax/Common.hs
  src/full/Agda/TypeChecking/Monad/Base.hs
  src/full/Agda/TypeChecking/Monad/Base.hs-boot
  src/full/Agda/TypeChecking/Monad/Debug.hs
  src/full/Agda/TypeChecking/Warnings.hs
Labels: refactor, pr: squash-me

#7039 Recompute blocker in equalSort
  src/full/Agda/TypeChecking/Conversion.hs
  test/Succeed/Issue7034-2.agda
  test/interaction/Issue7034.agda
  test/interaction/Issue7034.in
  test/interaction/Issue7034.out
Labels: constraints, sorts, internal-error, pr: squash-me
