Repository agda/agda, pull requests merged in 2023-05, with the labels that each got.

#6598 Increase laziness of builtin access in `fastReduce`
  src/full/Agda/TypeChecking/Monad/Builtin.hs
  src/full/Agda/TypeChecking/Reduce/Fast.hs
Labels: type: enhancement, performance, builtin, refactor, reduce-fast

#6600 Remove cabal flag `cpphs`
  .github/workflows/cabal.yml
  .github/workflows/stack-dry-run.yml
  .github/workflows/stack.yml
  Agda.cabal
  CHANGELOG.md
  doc/user-manual/getting-started/installation.rst
  src/github/workflows/cabal.yml
  src/github/workflows/stack-dry-run.yml
  src/github/workflows/stack.yml
Labels: CPP

#6601 Small haddock tweaks
  src/full/Agda/Syntax/Treeless.hs
Labels: haddock

#6604 Add a note for distinct, identical-looking extended lambdas
  src/full/Agda/TypeChecking/Errors.hs
  test/Fail/ExtLamNotEqual.agda
  test/Fail/ExtLamNotEqual.err
Labels: ux: error reporting

#6602 Fix #5992: Swap type argument order in Lens'
  src/full/Agda/Auto/Options.hs
  src/full/Agda/Compiler/Backend.hs
  src/full/Agda/Compiler/MAlonzo/Compiler.hs
  src/full/Agda/Compiler/Treeless/Erase.hs
  src/full/Agda/Interaction/Library/Base.hs
  src/full/Agda/Interaction/Library/Parse.hs
  src/full/Agda/Interaction/Options/Base.hs
  src/full/Agda/Interaction/Options/Lenses.hs
  src/full/Agda/Interaction/Options/Warnings.hs
  src/full/Agda/Syntax/Abstract/Name.hs
  src/full/Agda/Syntax/Common.hs
  src/full/Agda/Syntax/Concrete.hs
  src/full/Agda/Syntax/Concrete/Definitions/Monad.hs
  src/full/Agda/Syntax/Concrete/Name.hs
  src/full/Agda/Syntax/Internal.hs
  src/full/Agda/Syntax/Notation.hs
  src/full/Agda/Syntax/Parser/Alex.hs
  src/full/Agda/Syntax/Scope/Base.hs
  src/full/Agda/Syntax/TopLevelModuleName.hs
  src/full/Agda/Termination/Monad.hs
  src/full/Agda/TypeChecking/Free/Lazy.hs
  src/full/Agda/TypeChecking/Monad/Base.hs
  src/full/Agda/TypeChecking/Monad/Closure.hs
  src/full/Agda/TypeChecking/Monad/Constraints.hs
  src/full/Agda/TypeChecking/Monad/MetaVars.hs
  src/full/Agda/TypeChecking/Monad/State.hs
  src/full/Agda/TypeChecking/Reduce/Monad.hs
  src/full/Agda/TypeChecking/Rewriting/NonLinMatch.hs
  src/full/Agda/TypeChecking/Rules/LHS/Problem.hs
  src/full/Agda/TypeChecking/Rules/LHS/Unify/Types.hs
  src/full/Agda/TypeChecking/Serialise/Base.hs
  src/full/Agda/TypeChecking/Unquote.hs
  src/full/Agda/Utils/IndexedList.hs
  src/full/Agda/Utils/Lens.hs
  src/full/Agda/Utils/Lens/Examples.hs
  src/full/Agda/Utils/Memo.hs
  src/full/Agda/Utils/Trie.hs
  src/full/Agda/Utils/WithDefault.hs
Labels: refactor

#6609 readthedocs.org now needs a configuration file
  .github/workflows/test.yml
  .readthedocs.yaml
  src/github/workflows/test.yml
Labels: ux: documentation

#6608 --guarded does not require --cubical.
  doc/user-manual/language/guarded.lagda.rst
  doc/user-manual/language/index.rst
  doc/user-manual/tools/command-line-options.rst
Labels: ux: documentation, guarded cubical

#6610 Docs: bump Sphinx to 6.0.0
  doc/user-manual/conf.py
  doc/user-manual/requirements.txt
Labels: ux: documentation

#6607 Mention possibility of comment lines in libraries file.
  doc/user-manual/tools/package-system.rst
Labels: ux: documentation, ux: library management, pr: squash-me

#6611 Fixup PR #6556: help text: --erase-record-parameters implies --erasure
  src/full/Agda/Interaction/Options/Base.hs
Labels: ux: documentation, erasure

#6618 Fixup PR #6556 III: CHANGELOG and docs for --erased-matches.
  CHANGELOG.md
  doc/user-manual/tools/command-line-options.rst
Labels: ux: documentation, erasure

#6619 Represent builtin sorts via an enum not strings
  src/full/Agda/TypeChecking/Monad/Base.hs
  src/full/Agda/TypeChecking/Primitive.hs
  src/full/Agda/TypeChecking/Rules/Builtin.hs
  src/full/Agda/TypeChecking/Rules/Decl.hs
  src/full/Agda/TypeChecking/Serialise.hs
  src/full/Agda/TypeChecking/Serialise/Instances/Internal.hs
Labels: builtin, refactor, sorts

#6634 Implicitly import SSet from Agda.Primitive along with Prop & Set
  .hlint.yaml
  Agda.cabal
  CHANGELOG.md
  doc/user-manual/tools/command-line-options.rst
  src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs
  test/Fail/Issue3207.err
  test/Fail/Optimised-open.err
  test/Fail/Prop-Disabled.err
  test/Succeed/Issue5434.agda
  test/Succeed/Issue6073.agda
Labels: import, sorts, 2ltt

#6631 Print CheckArguments differently when the function returns a dummy
  src/full/Agda/TypeChecking/Pretty/Call.hs
  test/Fail/Issue6627.agda
  test/Fail/Issue6627.err
Labels: ux: error reporting

#6638 fix #6635: Switch the --count-clusters default to false
  src/full/Agda/Interaction/Options/Base.hs
Labels: ux: options, text-icu

#6644 [ refactor ] Introduce arity-generic killRangeN
  src/full/Agda/Syntax/Abstract.hs
  src/full/Agda/Syntax/Abstract/Name.hs
  src/full/Agda/Syntax/Common.hs
  src/full/Agda/Syntax/Concrete.hs
  src/full/Agda/Syntax/Internal.hs
  src/full/Agda/Syntax/Literal.hs
  src/full/Agda/Syntax/Position.hs
  src/full/Agda/TypeChecking/CompiledClause.hs
  src/full/Agda/TypeChecking/Coverage/SplitTree.hs
  src/full/Agda/TypeChecking/Monad/Base.hs
Labels: refactor

#6649 Compile `PrimLockUniv` as unit type
  src/full/Agda/Compiler/MAlonzo/Primitives.hs
  test/Compiler/simple/Guarded.agda
  test/Compiler/simple/Guarded.options
  test/Compiler/simple/Guarded.out
Labels: backend: ghc, guarded cubical

#6666 Handle copied definitions in unfolding clauses
  src/full/Agda/Syntax/Translation/AbstractToConcrete.hs
  src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs
  src/full/Agda/TypeChecking/Opacity.hs
  test/Succeed/OpaqueCopy.agda
Labels: opaque
