Repository agda/agda, pull requests merged in 2023-10, with the labels that each got.

#6874 Break cross-module SCC 1
  Agda.cabal
  src/full/Agda/Compiler/JS/Compiler.hs
  src/full/Agda/Syntax/Common.hs
  src/full/Agda/Syntax/Common/Aspect.hs
  src/full/Agda/Syntax/Common/Pretty.hs
  src/full/Agda/Syntax/Literal.hs
  src/full/Agda/Syntax/Position.hs
  src/full/Agda/Syntax/TopLevelModuleName.hs
  src/full/Agda/Syntax/TopLevelModuleName.hs-boot
  src/full/Agda/Syntax/TopLevelModuleName/Boot.hs
  src/full/Agda/Utils/FileName.hs
Labels: refactor, pr: squash-me

#6906 test-suite: Pacify GHC 9.8's new warning `x-partial`
  src/full/Agda/Utils/Cluster.hs
  src/full/Agda/Utils/List1.hs
  test/Internal/Utils/Cluster.hs
  test/Internal/Utils/Graph/AdjacencyMap/Unidirectional.hs
  test/Internal/Utils/RangeMap.hs
Labels: infra: test suite, ghc-9.8

#6907 Fix #6905: work around a bug in process-1.6.14..17
  test/Utils.hs
Labels: infra: test suite

#6603 Add `record where` syntax sugar
  CHANGELOG.md
  doc/user-manual/language/record-types.lagda.rst
  src/full/Agda/Syntax/Concrete.hs
  src/full/Agda/Syntax/Concrete/Generic.hs
  src/full/Agda/Syntax/Concrete/Pretty.hs
  src/full/Agda/Syntax/Parser/Parser.y
  src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs
  test/Fail/RecordWhere1.agda
  test/Fail/RecordWhere1.err
  test/Fail/RecordWhere2.agda
  test/Fail/RecordWhere2.err
  test/Succeed/RecordWhere.agda
  test/Succeed/RecordWhere.warn
Labels: records

#6912 Relax dependency bound to `split < 0.3`
  Agda.cabal
Labels: dependencies

#6903 Fix the spelling of "ambiguous"
  src/full/Agda/TypeChecking/Quote.hs
  test/Fail/AmbiguousQuote.agda
  test/Fail/AmbiguousQuote.err
  test/Succeed/Issue2360.agda
Labels: ux: error reporting, typo, pr: squash-me

#6863 toggle debug reporting via CPP
  .github/workflows/stack-dry-run.yml
  .github/workflows/test.yml
  Agda.cabal
  CHANGELOG.md
  Makefile
  doc/user-manual/getting-started/installation.rst
  doc/user-manual/tools/command-line-options.rst
  src/full/Agda/Compiler/Backend.hs
  src/full/Agda/Compiler/CallCompiler.hs
  src/full/Agda/Compiler/JS/Compiler.hs
  src/full/Agda/Compiler/MAlonzo/Compiler.hs
  src/full/Agda/Interaction/Imports.hs
  src/full/Agda/Interaction/Options/Base.hs
  src/full/Agda/Main.hs
  src/full/Agda/Syntax/Concrete/Operators/Parser/Monad.hs
  src/full/Agda/Syntax/Internal/SanityCheck.hs
  src/full/Agda/TypeChecking/Monad/Debug.hs
  src/full/Agda/TypeChecking/Monad/Statistics.hs
  src/full/Agda/TypeChecking/Reduce/Monad.hs
  src/full/Agda/TypeChecking/Serialise.hs
  src/full/Agda/TypeChecking/Serialise/Base.hs
  src/github/workflows/stack-dry-run.yml
  src/github/workflows/test.yml
Labels: performance, debug

#6899 Perf fixes and more benchmark data in TypeChecking.DeadCode
  src/full/Agda/Benchmarking.hs
  src/full/Agda/Syntax/Internal/Names.hs
  src/full/Agda/TypeChecking/DeadCode.hs
  src/full/Agda/Utils/HashTable.hs
Labels: performance, dead-code

#6922 doc installation Fedora: fixup rst link markup
  doc/user-manual/getting-started/installation.rst
Labels: ux: installation, user-manual

#6925 Re #6746: bump tested-with etc to GHC 9.8.1; bump deps in tools
  Agda.cabal
  CHANGELOG.md
  doc/user-manual/getting-started/installation.rst
  src/agda-bisect/agda-bisect.cabal
  src/agda-bisect/cabal.project
  src/release-tools/closed-issues-for-milestone/closed-issues-for-milestone.cabal
  src/size-solver/size-solver.cabal
Labels: ghc-9.8

#6938 Instantiate all metas before retrieving blockers in `getLockVar`.
  src/full/Agda/TypeChecking/Lock.hs
  test/Fail/Issue6913.agda
  test/Fail/Issue6913.err
Labels: constraints, guarded cubical, internal-error

#6921 Record UnifyIndices bench cost under Coverage
  src/full/Agda/TypeChecking/Coverage.hs
Labels: performance, debug

#6942 [ fix #6941 ] Ignore abstract mode in `getOutputTypeName`
  src/full/Agda/TypeChecking/Telescope.hs
  test/Succeed/Issue6941.agda
Labels: abstract, instance, opaque

#6946 Separate parameters with space when pretty-printing
  src/full/Agda/Syntax/Concrete/Pretty.hs
  test/Fail/Issue6675.err
  test/Fail/NoLetInRecordTele.err
  test/Fail/NoLetInRecordTele2.err
  test/Fail/TelescopingLetDataRecord.err
  test/Succeed/Issue3989.warn
Labels: type: bug, ux: error reporting
