Repository agda/agda, pull requests merged in 2023-04, with the labels that each got.

#6575 Aggressively inline VALU typeclass methods
  src/full/Agda/TypeChecking/Serialise/Base.hs
Labels: type: enhancement, performance, serialization

#6580 fixup: don't reify DefP clauses when printing an extended lambda
  src/full/Agda/Syntax/Translation/InternalToAbstract.hs
  test/Fail/ExtLamDefp.agda
  test/Fail/ExtLamDefp.err
  test/interaction/Issue4679.out
Labels: extended lambdas, cubical-compatible

#6583 Treat no-eta pattern records as data types in transp
  src/full/Agda/TypeChecking/Primitive/Cubical.hs
  src/full/Agda/TypeChecking/Rules/Record.hs
  test/Succeed/Issue6581.agda
Labels: eta, records, cubical

#6590 Split --help=warning in benign/severe and sort alphabetically
  src/full/Agda/Interaction/Options/Warnings.hs
Labels: ux: documentation, ux: warnings

#6597 Convert `SmallSet` to be a bitset
  src/full/Agda/TypeChecking/Monad/Base.hs
  src/full/Agda/Utils/SmallSet.hs
  test/Internal/Utils/SmallSet.hs
Labels: performance
