Repository agda/agda, pull requests merged in 2024-02, with the labels that each got.

#7097 Float DefP clauses above catch-alls
  src/full/Agda/TypeChecking/CompiledClause/Compile.hs
  test/Fail/Issue7033a.agda
  test/Fail/Issue7033a.err
  test/Fail/Issue7033b.agda
  test/Fail/Issue7033b.err
Labels: clause-compiler, cubical

#6974 #6972: Also save backcopies in interface file
  src/full/Agda/Interaction/Imports.hs
  src/full/Agda/TypeChecking/Opacity.hs
  test/Succeed/Issue6972a.agda
  test/Succeed/Issue6972b.agda
  test/Succeed/Issue6972c.agda
Labels: opaque

#7102 Bump stack-*.yaml to latest 9.6.4 and 9.8.1 snapshots
  stack-9.6.4.yaml
  stack-9.8.1.yaml
Labels: infra: github workflows

#7106 #7105 Do not try to fold let-bindings during printing of the helper function
  src/full/Agda/Interaction/BasicOps.hs
  test/interaction/Issue7105.agda
  test/interaction/Issue7105.in
  test/interaction/Issue7105.out
Labels: ux: generate helper

#7112 Use a separate warning for duplicated interface files
  doc/user-manual/tools/command-line-options.rst
  src/full/Agda/Interaction/FindFile.hs
  src/full/Agda/Interaction/Highlighting/Generate.hs
  src/full/Agda/Interaction/Imports.hs
  src/full/Agda/Interaction/Options/Warnings.hs
  src/full/Agda/TypeChecking/Monad/Base.hs
  src/full/Agda/TypeChecking/Pretty/Warning.hs
  src/full/Agda/TypeChecking/Serialise.hs
  src/full/Agda/TypeChecking/Serialise/Instances/Errors.hs
Labels: ux: warnings

#7129 Delete Travis CI files
  .travis.yml
  .travis/cabal_install
  .travis/header.sh
Labels: devx

#7122 Fix for issue #7113
  src/full/Agda/TypeChecking/Rules/Term.hs
  test/Succeed/Issue7113.agda
Labels: with, instance

#7131 Allow Win32-2.14
  Agda.cabal
Labels: platform: windows, dependencies

#6536 Janitorial Changes to agda-mode
  src/agda-mode/Main.hs
  src/data/emacs-mode/.dir-locals.el
  src/data/emacs-mode/agda-input.el
  src/data/emacs-mode/agda2-abbrevs.el
  src/data/emacs-mode/agda2-highlight.el
  src/data/emacs-mode/agda2-mode.el
  src/data/emacs-mode/agda2-queue.el
  src/data/emacs-mode/agda2.el
  src/data/emacs-mode/eri.el
Labels: ux: emacs, refactor

#7121 Update installation.rst
  doc/user-manual/getting-started/installation.rst
Labels: ux: documentation, pr: squash-me
