Repository agda/agda, pull requests merged in 2025-01, with the labels that each got.

#7670 Fix typo `COMPILED`
  doc/user-manual/language/foreign-function-interface.lagda.rst
Labels: user-manual

#7676 Remove `--local-interfaces` and warning `DuplicateInterfaceFiles`
  CHANGELOG.md
  doc/user-manual/tools/command-line-options.rst
  src/full/Agda/Interaction/FindFile.hs
  src/full/Agda/Interaction/Highlighting/Generate.hs
  src/full/Agda/Interaction/Options/Base.hs
  src/full/Agda/Interaction/Options/Types.hs
  src/full/Agda/Interaction/Options/Warnings.hs
  src/full/Agda/TypeChecking/Monad/Base.hs
  src/full/Agda/TypeChecking/Pretty/Warning.hs
  src/full/Agda/TypeChecking/Serialise/Instances/Errors.hs
  test/test-suite-covers-warnings.sh
Labels: interface, ux: library management

#7677 Setup: fix `wantInterfaces` check
  Setup.hs
Labels: ux: installation, Setup.hs

#7679 Disallow several .agda-lib files in the project root (#7678)
  CHANGELOG.md
  doc/user-manual/tools/package-system.rst
  src/full/Agda/Interaction/Library.hs
  src/full/Agda/Interaction/Library/Base.hs
  src/full/Agda/TypeChecking/Monad/Options.hs
  src/full/Agda/Utils/IO.hs
  test/Fail/Installed.err
  test/Fail/Issue7678/Issue7678.agda
  test/Fail/Issue7678/Issue7678.err
  test/Fail/Issue7678/one.agda-lib
  test/Fail/Issue7678/two.agda-lib
  test/Fail/Tests.hs
  test/Succeed/installed-libs/libraries
  test/Succeed/succeed2.agda-lib
Labels: ux: library management, pr: preserve commits

#7684 Fix #7683: remove Eliminators.hs-boot
  src/full/Agda/TypeChecking/Eliminators.hs-boot
Labels: style

#7688 Add some links to lecture notes and videos on Agda
  doc/user-manual/getting-started/tutorial-list.rst
Labels: ux: documentation

#7697 Fix #7696: Add missing `addContext` when splitting on literals
  src/full/Agda/TypeChecking/Rules/LHS.hs
  test/Succeed/Issue7696.agda
Labels: de-Bruijn, internal-error

#7698 [doc] sphinx: python virtual environment, requirement sphinxcontrib-jquery
  .github/workflows/Makefile
  .github/workflows/user_manual.yml
  doc/user-manual/Makefile
  doc/user-manual/requirements.txt
  src/github/workflows/user_manual.yml
Labels: ux: documentation, not-in-changelog
