Repository agda/agda, pull requests merged in 2025-07, with the labels that each got.

#7908 Drop GHC 9.0 and below and bump dependencies to LTS 20.26
  .github/workflows/cabal.yml
  .github/workflows/stack.yml
  Agda.cabal
  doc/user-manual/getting-started/installation.rst
  src/full/Agda/Interaction/Highlighting/LaTeX/Base.hs
  src/full/Agda/Interaction/JSON.hs
  src/full/Agda/Interaction/Monad.hs
  src/full/Agda/TypeChecking/Conversion.hs
  src/full/Agda/TypeChecking/Monad/Base.hs
  src/full/Agda/Utils/IArray.hs
  src/full/Agda/Utils/List1.hs
  src/full/Agda/Utils/VarSet.hs
  src/github/workflows/cabal.yml
  src/github/workflows/stack.yml
  src/setup/Agda/VersionCommit.hs
  stack-8.10.7.yaml
  stack-8.8.4.yaml
  stack-9.0.2.yaml
Labels: ghc support, ghc-8

#7922 Mimer refactor
  Agda.cabal
  src/full/Agda/Interaction/InteractionTop.hs
  src/full/Agda/Mimer/Mimer.hs
  src/full/Agda/Mimer/Monad.hs
  src/full/Agda/Mimer/Types.hs
  src/full/Agda/TypeChecking/Monad/Debug.hs
Labels: pr: squash-me, Mimer

#7951 Improve module checkpointing performance
  src/full/Agda/Interaction/BasicOps.hs
  src/full/Agda/Syntax/Abstract/Name.hs
  src/full/Agda/TypeChecking/Monad/Base.hs
  src/full/Agda/TypeChecking/Monad/Context.hs
  src/full/Agda/TypeChecking/Monad/Signature.hs
  src/full/Agda/TypeChecking/Rules/Record.hs
  test/Succeed/RecordFieldAndModules.agda
Labels: performance, checkpoints

#7986 New option --ghc-trace to instrument code with call trace
  CHANGELOG.md
  doc/user-manual/tools/compilers.lagda.rst
  src/full/Agda/Compiler/MAlonzo/Compiler.hs
  src/full/Agda/Compiler/MAlonzo/Misc.hs
  test/Compiler/simple/VecReverseErasedTrace.agda
  test/Compiler/simple/VecReverseErasedTrace.options
  test/Compiler/simple/VecReverseErasedTrace.out
Labels: backend: ghc, ux: options

#7995 Fix #7994: warn about @tactic attributes ignored in declarations
  CHANGELOG.md
  doc/user-manual/tools/command-line-options.rst
  src/full/Agda/Interaction/Highlighting/Generate.hs
  src/full/Agda/Interaction/Options/Warnings.hs
  src/full/Agda/Syntax/Concrete.hs
  src/full/Agda/Syntax/Concrete/Definitions.hs
  src/full/Agda/Syntax/Concrete/Definitions/Errors.hs
  src/full/Agda/TypeChecking/Serialise.hs
  src/full/Agda/TypeChecking/Serialise/Instances/Errors.hs
  test/Succeed/Issue7777.agda
  test/Succeed/Issue7777.warn
Labels: parser, tactic

#8002 Redo: Fix #7508: remove unused-arg optimization from the JS backend (#7509)
  src/full/Agda/Compiler/JS/Compiler.hs
  src/full/Agda/Compiler/ToTreeless.hs
  test/Compiler/simple/Issue7508.agda
  test/Compiler/simple/Issue7508.out
Labels: backend: js, erasure

#8007 Add unused-binds warning in Agda.Syntax.Concrete.*
  src/full/Agda/Syntax/Concrete/Attribute.hs
  src/full/Agda/Syntax/Concrete/Definitions.hs
  src/full/Agda/Syntax/Concrete/Definitions/Errors.hs
  src/full/Agda/Syntax/Concrete/Definitions/Monad.hs
  src/full/Agda/Syntax/Concrete/Definitions/Types.hs
  src/full/Agda/Syntax/Concrete/Fixity.hs
  src/full/Agda/Syntax/Concrete/Generic.hs
  src/full/Agda/Syntax/Concrete/Glyph.hs
  src/full/Agda/Syntax/Concrete/Name.hs
  src/full/Agda/Syntax/Concrete/Operators.hs
  src/full/Agda/Syntax/Concrete/Operators/Parser.hs
  src/full/Agda/Syntax/Concrete/Operators/Parser/Monad.hs
  src/full/Agda/Syntax/Concrete/Pattern.hs
  src/full/Agda/Syntax/Concrete/Pretty.hs
Labels: refactor, style

#8008 flake: fix overlay
  .gitignore
  flake.nix
Labels: platform: nix

#8020 record where: Fix impossible with named module copy
  src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs
  test/Succeed/RecordWhereNamedCopy.agda
Labels: record where

#8022 fixup: eta for cubical primitives against neutrals
  src/full/Agda/TypeChecking/Conversion.hs
  test/Succeed/TranspReflPair.agda
Labels: cubical

#8025 Re #1499 #5277 better formatting for error AmbiguousFunClauses
  src/full/Agda/Syntax/Concrete/Definitions/Errors.hs
  test/Fail/Issue1499.agda
  test/Fail/Issue1499.err
Labels: ux: error reporting, nice
